name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.16

      - name: Cache ~/.pnpm-store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-16.x-test-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-16.x-test-${{ env.cache-name }}-
            ${{ runner.os }}-16.x-test-
            ${{ runner.os }}-
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: Unit tests
        run: pnpm test

      - name: e2e tests
        run: pnpm e2e
